---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.longhorn.io
    chart: longhorn
    targetRevision: 1.7.2
    helm:
      releaseName: longhorn
      values: |
        persistence:
          defaultClass: true
          defaultClassReplicaCount: 2
        defaultSettings:
          defaultDataPath: /var/lib/longhorn
          defaultReplicaCount: 2
          createDefaultDiskLabeledNodes: false
        ingress:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
